# Generated by Django 4.2.7 on 2025-07-10 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        help_text="SMTP server hostname (e.g., smtp.gmail.com)",
                        max_length=255,
                    ),
                ),
                (
                    "smtp_port",
                    models.IntegerField(
                        default=587,
                        help_text="SMTP server port (587 for TLS, 465 for SSL, 25 for no encryption)",
                    ),
                ),
                (
                    "smtp_username",
                    models.CharField(
                        help_text="SMTP username (usually your email address)",
                        max_length=255,
                    ),
                ),
                (
                    "smtp_password",
                    models.TextField(
                        help_text="SMTP password or app-specific password"
                    ),
                ),
                (
                    "sender_email",
                    models.EmailField(
                        help_text="Default sender email address", max_length=254
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(
                        default="ConvaBI System",
                        help_text="Default sender name",
                        max_length=255,
                    ),
                ),
                (
                    "encryption",
                    models.CharField(
                        choices=[("none", "None"), ("tls", "TLS"), ("ssl", "SSL")],
                        default="tls",
                        help_text="Email encryption method",
                        max_length=10,
                    ),
                ),
                (
                    "use_tls",
                    models.BooleanField(default=True, help_text="Use TLS encryption"),
                ),
                (
                    "use_ssl",
                    models.BooleanField(default=False, help_text="Use SSL encryption"),
                ),
                (
                    "timeout",
                    models.IntegerField(
                        default=30, help_text="Connection timeout in seconds"
                    ),
                ),
                (
                    "fail_silently",
                    models.BooleanField(
                        default=False, help_text="Fail silently on email errors"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this email configuration is active",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the email configuration has been tested successfully",
                    ),
                ),
                (
                    "last_tested",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the email configuration was last tested",
                        null=True,
                    ),
                ),
                (
                    "test_status",
                    models.TextField(blank=True, help_text="Result of the last test"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this configuration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Configuration",
                "verbose_name_plural": "Email Configurations",
                "db_table": "app_email_config",
            },
        ),
    ]
