# Generated by Django 4.2.7 on 2025-07-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_emailconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmconfig",
            name="base_url",
            field=models.URLField(
                blank=True,
                default="http://localhost:11434",
                help_text="Base URL for API calls (for custom endpoints)",
            ),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="model_name",
            field=models.CharField(
                default="llama3.2:3b",
                help_text="Name of the model to use",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="llmconfig",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("azure", "Azure OpenAI"),
                    ("local", "Local LLM (Ollama)"),
                    ("anthropic", "Anthropic"),
                    ("google", "Google AI"),
                ],
                default="local",
                help_text="LLM provider to use",
                max_length=50,
            ),
        ),
    ]
