services:
  postgres:
    image: postgres:15
    container_name: convabc_postgres
    environment:
      POSTGRES_DB: convabi
      POSTGRES_USER: convabiuser
      POSTGRES_PASSWORD: convabipass
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - convabc_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: convabc_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - convabc_network
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: convabc_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - convabc_network
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: convabc_web
    volumes:
      - ./django_dbchat:/app/django_dbchat
      - ./data:/app/data
      - ./logs:/app/logs
      - ./media:/app/media
      - ./backups:/app/backups
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DATABASE_URL=postgresql://convabiuser:convabipass@postgres:5432/convabi
      - POSTGRES_HOST=postgres
      - USE_REDIS=True
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - OPENAI_API_KEY=
      - OLLAMA_BASE_URL=http://ollama:11434
    networks:
      - convabc_network
    depends_on:
      - postgres
      - redis
      - ollama
    restart: unless-stopped

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: convabc_celery
    command: celery -A dbchat_project worker --loglevel=info --concurrency=4 --queues=*
    volumes:
      - ./django_dbchat:/app/django_dbchat
      - ./data:/app/data
      - ./logs:/app/logs
      - ./media:/app/media
      - ./backups:/app/backups
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
      - DATABASE_URL=postgresql://convabiuser:convabipass@postgres:5432/convabi
      - POSTGRES_HOST=postgres
      - USE_REDIS=True
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - OPENAI_API_KEY=
      - OLLAMA_BASE_URL=http://ollama:11434
    networks:
      - convabc_network
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    working_dir: /app/django_dbchat

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: convabc_celery_beat
    command: celery -A dbchat_project beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./django_dbchat:/app/django_dbchat
      - ./data:/app/data
      - ./logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
      - DATABASE_URL=postgresql://convabiuser:convabipass@postgres:5432/convabi
      - POSTGRES_HOST=postgres
      - USE_REDIS=True
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    networks:
      - convabc_network
    depends_on:
      - redis
      - postgres
      - web
    restart: unless-stopped
    working_dir: /app/django_dbchat

volumes:
  postgres_data:
  redis_data:
  ollama_data:

networks:
  convabc_network:
    driver: bridge 