# Generated by Django 4.2.7 on 2025-07-14 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "license_code",
                    models.CharField(
                        max_length=16, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[("creator", "Creator"), ("viewer", "Viewer")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("max_users", models.IntegerField(default=1)),
                ("features", models.JSONField(blank=True, default=dict)),
                ("created_by", models.CharField(default="system", max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "License",
                "verbose_name_plural": "Licenses",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="LicenseValidationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_code", models.CharField(max_length=16)),
                ("validation_result", models.BooleanField()),
                ("error_message", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "License Validation Log",
                "verbose_name_plural": "License Validation Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_by", models.CharField(default="admin", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deactivated_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("deactivation_reason", models.TextField(blank=True)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_licenses",
                        to="licensing.license",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_licenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User License",
                "verbose_name_plural": "User Licenses",
                "ordering": ["-assigned_at"],
                "unique_together": {("user", "license")},
            },
        ),
    ]
