# Default configuration for Local LLM
LOCAL_LLM_BASE_URL = "http://localhost:11434/v1" # Default for Ollama
LOCAL_LLM_MODEL_NAME = "sqlcoder:latest"    # Example model, change as needed
LOCAL_LLM_API_KEY = ""                        # Optional: API key if your local LLM requires one

# Example for Email (SendGrid - replace with your actual credentials)
# SENDGRID_API_KEY = "YOUR_SENDGRID_API_KEY"
# DEFAULT_SENDER_EMAIL = "your_email@example.com"
